import type { ItemOS, OrdemServico, Produto } from "./tipos";

const horasAtras = (h: number) => new Date(Date.now() - h * 36e5).toISOString();

const VEICULOS = {
  v1: { placa: "ABC-1D23", marca: "VW", modelo: "Gol", ano: 2016 },
  v2: { placa: "RXY-7H89", marca: "Chevrolet", modelo: "Onix", ano: 2020 },
  v3: { placa: "BDX-4A17", marca: "Honda", modelo: "CG 160 Titan", ano: 2022 },
};

const CLIENTES = {
  c1: { nome: "Rogério Baptista", telefone: "5541988887777" },
  c2: { nome: "Marina Vasques", telefone: "5541977776666" },
  c3: { nome: "Carlos Bittencourt", telefone: "5541998712230" },
};

export const ORDENS_DEMO: OrdemServico[] = [
  {
    id: "o1",
    numero: 1041,
    status: "em_execucao",
    km_entrada: 128500,
    relato_cliente: "Barulho na frente ao frear.",
    diagnostico: "Pastilhas dianteiras no limite e disco com sulco leve.",
    valor_pecas: 149,
    valor_servicos: 120,
    valor_desconto: 0,
    valor_total: 269,
    aberta_em: horasAtras(80),
    finalizada_em: null,
    entregue_em: null,
    veiculo_id: "v1",
    cliente_id: "c1",
    veiculos: VEICULOS.v1,
    clientes: CLIENTES.c1,
  },
  {
    id: "o2",
    numero: 1042,
    status: "aguardando_aprovacao",
    km_entrada: 61200,
    relato_cliente: "Revisão dos 60 mil.",
    diagnostico: null,
    valor_pecas: 81.9,
    valor_servicos: 350,
    valor_desconto: 0,
    valor_total: 431.9,
    aberta_em: horasAtras(30),
    finalizada_em: null,
    entregue_em: null,
    veiculo_id: "v2",
    cliente_id: "c2",
    veiculos: VEICULOS.v2,
    clientes: CLIENTES.c2,
  },
  {
    id: "o3",
    numero: 1043,
    status: "diagnostico",
    km_entrada: 18420,
    relato_cliente: "Ruído metálico no motor em marcha lenta.",
    diagnostico: null,
    valor_pecas: 0,
    valor_servicos: 0,
    valor_desconto: 0,
    valor_total: 0,
    aberta_em: horasAtras(3),
    finalizada_em: null,
    entregue_em: null,
    veiculo_id: "v3",
    cliente_id: "c3",
    veiculos: VEICULOS.v3,
    clientes: CLIENTES.c3,
  },
  {
    id: "o4",
    numero: 1039,
    status: "entregue",
    km_entrada: 59800,
    relato_cliente: "Troca de óleo.",
    diagnostico: "Óleo vencido, filtro saturado.",
    valor_pecas: 81.9,
    valor_servicos: 90,
    valor_desconto: 0,
    valor_total: 171.9,
    aberta_em: horasAtras(24 * 14),
    finalizada_em: horasAtras(24 * 13),
    entregue_em: horasAtras(24 * 13),
    veiculo_id: "v2",
    cliente_id: "c2",
    veiculos: VEICULOS.v2,
    clientes: CLIENTES.c2,
  },
  {
    id: "o5",
    numero: 1040,
    status: "finalizado",
    km_entrada: 127200,
    relato_cliente: "Bateria arriando.",
    diagnostico: "Bateria sem carga, alternador ok.",
    valor_pecas: 459,
    valor_servicos: 80,
    valor_desconto: 20,
    valor_total: 519,
    aberta_em: horasAtras(24 * 5),
    finalizada_em: horasAtras(24 * 4),
    entregue_em: null,
    veiculo_id: "v1",
    cliente_id: "c1",
    veiculos: VEICULOS.v1,
    clientes: CLIENTES.c1,
  },
];

export const ITENS_DEMO: ItemOS[] = [
  { id: "i1", os_id: "o1", tipo: "peca", descricao: "Pastilha de freio dianteira", quantidade: 1, valor_unit: 149 },
  { id: "i2", os_id: "o1", tipo: "servico", descricao: "Troca de pastilhas dianteiras", quantidade: 1, valor_unit: 120 },
  { id: "i3", os_id: "o2", tipo: "peca", descricao: "Óleo 5W30 sintético 1L", quantidade: 1, valor_unit: 49.9 },
  { id: "i4", os_id: "o2", tipo: "peca", descricao: "Filtro de óleo", quantidade: 1, valor_unit: 32 },
  { id: "i5", os_id: "o2", tipo: "servico", descricao: "Revisão completa", quantidade: 1, valor_unit: 350 },
];

export const PRODUTOS_DEMO: Produto[] = [
  { id: "p1", nome: "Óleo 5W30 sintético 1L", sku: "OL-5W30", preco_venda: 49.9, preco_custo: 28, estoque_min: 12, unidade: "UN", ativo: true, saldo: 22, situacao: "ok" },
  { id: "p2", nome: "Filtro de óleo", sku: "FO-001", preco_venda: 32, preco_custo: 15, estoque_min: 6, unidade: "UN", ativo: true, saldo: 4, situacao: "critico" },
  { id: "p3", nome: "Pastilha de freio dianteira", sku: "PF-D01", preco_venda: 149, preco_custo: 78, estoque_min: 4, unidade: "JG", ativo: true, saldo: 0, situacao: "zerado" },
  { id: "p4", nome: "Bateria 60Ah", sku: "BAT-60", preco_venda: 459, preco_custo: 290, estoque_min: 2, unidade: "UN", ativo: true, saldo: 3, situacao: "ok" },
];
